stages:
  - build
  - deploy
  - test
variables:
  PUSH_VERSION: "v1"
  HUB_USER: "kuofrank"
  HUB_PWD: "Systex@820214"
  
feat-build:
  stage: build
  only:
    - feature
  script:
    - echo "dev build"
    - pwd
    - ls
    - export #印出環境變數
    - mvn compile jib:build
#    - mvn compile jib:build \
#      -Djib.to.auth.username=${CI_REGISTRY_USER} \
#      -Djib.to.auth.password=${CI_REGISTRY_PASSWORD} \
#      -Djib.to.image=${CI_REGISTRY_IMAGE}:latest

feat-deploy:
  stage: deploy
  only:
    - feature
  script:
    - echo "dev deploy"

#feat-test:
#  stage: test
#  only:
#    - feature
#  script:
#    - echo "dev testing"